server:
  port: 8080


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/eboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root