spring:
  profiles:
    active: dev
  application:
    name: eboot-consumer
  boot:
    admin:
      client:
        url: "http://192.168.10.1:8091"
        instance:
          prefer-ip: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.130:8848
  zipkin:
    base-url: http://192.168.10.130:9411
  sleuth:
    sampler:
      probability: 1 #样本采集量,默认0.1


server:
  port: 8111


feign:
  hystrix:
    # 开启熔断器
    enabled: true
