spring:
  profiles:
    active: dev
  application:
    name: eboot-monitor
  cloud:
    consul:
      host: 192.168.10.130
      port: 8500
      discovery:
        # 注册到consul的服务名称
        serviceName: ${spring.application.name}
        prefer-ip-address: true


server:
  port: 8091



