spring:
  profiles:
    active: dev
  application:
    name: eboot-zuul
  boot:
    admin:
      client:
        url: "http://192.168.10.1:8091"
        instance:
          prefer-ip: true
  cloud:
    consul:
      host: 192.168.10.130
      port: 8500
      discovery:
        # 注册到consul的服务名称
        serviceName: ${spring.application.name}
        prefer-ip-address: true


server:
  port: 8131


zuul:
  routes:
    eboot-consumer:
      path: /eboot-consumer/**
      serviceId: eboot-consumer  # 转发到消费者