spring:
  profiles:
    active: dev
  application:
    name: eboot-zuul
  boot:
    admin:
      client:
        url: "http://192.168.10.1:8091"
        instance:
          prefer-ip: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.130:8848


server:
  port: 8131


zuul:
  routes:
    eboot-consumer:
      path: /eboot-consumer/**
      serviceId: eboot-consumer  # 转发到消费者