spring:
  profiles:
    active: dev
  application:
    name: eboot-gateway
  boot:
    admin:
      client:
        url: "http://192.168.10.1:8091"
        instance:
          prefer-ip: true
  cloud:
    consul:
      host: 192.168.10.130
      port: 8500
      discovery:
        # 注册到consul的服务名称
        serviceName: ${spring.application.name}
        prefer-ip-address: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            exposedHeaders:
              - content-type
            allowedHeaders:
              - content-type
            allowCredentials: true
            allowedMethods:
              - GET
              - POST


gateway:
  token:
    # 头
    header: token
    # 加密密钥
    secret: abcdefgh
    # 有效期  30 * 60 * 1000 毫秒
    expire_time: 1800000
    # 忽略路径
    ignored-path:
      - /eboot-sys/oauth/
      - /eboot-sys/druid
      - /eboot-sys/swagger-ui.html
      - /eboot-sys/swagger-resources
      - /eboot-sys/v2/api-docs
      - /eboot-sys/webjars/
      - /eboot-sys/kaptcha/
      - /eboot-sys/actuator
      - /eboot-sys/login
      - /eboot-sys/logout
      - /eboot-sys/csrf
      - /eboot-sys/favicon.ico

server:
  port: 8141


