spring:
  profiles:
    active: dev
  application:
    name: eboot-producer
  boot:
    admin:
      client:
        url: "http://192.168.10.1:8091"
        instance:
          prefer-ip: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.130:8848


server:
  port: 8101



