spring:
  profiles:
    active: dev
  application:
    name: eboot-hystrix
  boot:
    admin:
      client:
        url: "http://localhost:8091"
        instance:
          prefer-ip: true
  cloud:
    consul:
      host: 192.168.10.128
      port: 8500
      discovery:
        # 注册到consul的服务名称
        serviceName: ${spring.application.name}
        prefer-ip-address: true

turbine:
  instanceUrlSuffix: hystrix.stream    # 指定收集路径
  appConfig: eboot-consumer    # 指定了需要收集监控信息的服务名，多个以“,”进行区分
  clusterNameExpression: "'default'"    # 指定集群名称,若为default则为默认集群，多个集群则通过此配置区分
  combine-host-port: true    # 此配置默认为false，则服务是以host进行区分，若设置为true则以host+port进行区分


server:
  port: 8121

