spring:
  profiles:
    active: dev
  application:
    name: eboot-sys
  datasource:
    name: mysql1
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_empty
  boot:
    admin:
      client:
        url: "http://192.168.10.1:8091"
        instance:
          prefer-ip: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.130:8848

mybatis:
  # 映射文件位置
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
  #config-location:  classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.glacier.**.entity
  configuration:
    lazy-loading-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    auto-mapping-unknown-column-behavior: warning
    use-generated-keys: true
    aggressive-lazy-loading: false

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

auth:


config:
  jwt:
    # 头
    header: token
    # 加密密钥
    secret: abcdefgh
    # 有效期  30 * 60 * 1000 毫秒
    expire_time: 1800000
    ignored-path:
      - /login
      - /logout
      - /favicon.ico
      - /static/**
      - /webjars/**
      - /actuator/**
      - /druid/**
      - /swagger-ui.html
      - /swagger-resources/**
      - /v2/api-docs

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always